# General
spring.config.import=optional:file:.env[.properties]

spring.application.name=Simple-backend

# Default profile
spring.profiles.active=${SPRING_ACTIVE_PROFILE:development}

spring.main.allow-circular-references=true