apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-cnpg-cluster
spec:
  instances: 3
  image: ghcr.io/cloudnative-pg/postgresql:16.2
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: mydatabase
      owner: myuser
  postgresql:
    parameters:
      shared_preload_libraries: 'pgaudit'