apiVersion: v1
kind: Service
metadata:
  name: spring-engine-service
  labels:
    app: spring-engine
spec:
  selector:
    app: spring-engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP